#version: "3.8"

#services:
#  backend:
#    build:
#      context: ./backend/
#    environment:
#      DB_HOST: db
#      DB_PORT: 5432
#      DB_USER: postgres
#      DB_PASSWORD: 0000
#      DB_NAME: testdb
#    command: ["bash", "-c", "python init_db.py && flask run --host=0.0.0.0 --port=5000"]
#    depends_on:
#      - db
#  db:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: testdb
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 0000
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data


#  frontend:
#    build:
#      context: ./frontend/
#      dockerfile: Dockerfile
#    ports:
#      - "8080:80"
#    depends_on:
#      - backend

#volumes:
#  postgres_data:
