apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000          # Port your app is listening on
      targetPort: 5000    # Container port
      nodePort: 30002     # Expose on NodePort 30002
  type: NodePort          # Expose service externally
