apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: idrissfth/backend:latest
          env:
            - name: DB_HOST
              value: "postgres"   # This should be the service name
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "0000"
            - name: DB_NAME
              value: "testdb"
          ports:
            - containerPort: 5000
