apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80          # Expose the frontend on port 80
      targetPort: 80    # Container port
      nodePort: 30001   # Expose on NodePort 30001
  type: NodePort        # Expose service externally
